### ISSUE TITLE
Add subworkflows

### ISSUE THREAD

**Issue by FernandoDuarteF** [nf-core/genomeqc#17]

**Comment by chriswyatt1** [comment]
https://github.com/Eco-Flow/genomeqc/pull/19

**Comment by FernandoDuarteF** [comment]
TIDK was added in [239e64a](https://github.com/Eco-Flow/genomeqc/commit/239e64ad333057256c4c06eb9c328a40f98fb385).

**Comment by chriswyatt1** [comment]
Great, will close
