### ISSUE TITLE
Add ncbigenomedownload module

### ISSUE THREAD

**Issue by FernandoDuarteF** [nf-core/genomeqc#2]
The ncbigenomedownload module from nf-core requires a file with a list of accessions, and, therefore, needs a path as input. Excon, which I'm trying to mimic here, requires a value string as input.

To fix this problem, at least temporariIy, I added in ``modules/local/create_path.csv`` a module that creates one file per species which contains one single accession, which is then used as an input by ncbigenomedownload.

**Comment by chriswyatt1** [comment]
Great, nice to see it running the first step:

https://github.com/Eco-Flow/genomeqc/pull/7
