### ISSUE TITLE
Add all the modules

### ISSUE THREAD

**Issue by FernandoDuarteF** [nf-core/genomeqc#3]
Might be a good idea to add an item per module in the Todo list in the genomeqc plan Project.

**Comment by FernandoDuarteF** [comment]
Modules added so far:

**nf-core:**
* NCBIGENOMEDOWNLOAD
* GFFREAD
* AGAT_SPSTATISTICS
* QUAST
* BUSCO
* PIGZ_UNCOMPRESS
* ORTHOFINDER

**Local:**
* LONGEST (from synteny)
* CREAT_PATH (for ncbigenomedownload)

**Comment by chriswyatt1** [comment]
Complete
