### ISSUE TITLE
Quast doesn't cache every time

### ISSUE THREAD

**Issue by chriswyatt1** [nf-core/genomeqc#33]
Seems to keep repeating previously done runs with `-resume`

My command:

`nextflow run main.nf -resume -profile docker,test --outdir results`

**Comment by FernandoDuarteF** [comment]
This is happening becuase QUAST inputs are out of sync.

**Comment by FernandoDuarteF** [comment]
Solved in [de9a0d7](https://github.com/nf-core/genomeqc/commit/de9a0d7928502b33b1cc9c323e5f8cac8f11a888).
