### ISSUE TITLE
BUSCO runs on longest isoforms

### ISSUE THREAD

**Issue by FernandoDuarteF** [nf-core/genomeqc#38]
For now, we are using the longest isoforms for each gene to run BUSCO. Might or might not be the proper way to run it

**Comment by chriswyatt1** [comment]
https://github.com/orgs/nf-core/projects/76

**Comment by FernandoDuarteF** [comment]
BUSCO developers recommend filtering the gff files to get the longest isoform of each gene before runnign BUSCO.

See [BUSCO protocols](https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpz1.323).
