### ISSUE TITLE
Add `merqury` to pipeline

### ISSUE THREAD

**Issue by chriswyatt1** [nf-core/genomeqc#42]
Example from Usman: https://github.com/Plant-Food-Research-Open/assemblyqc

Used in genome only mode.  Already an nf-core module

**Comment by stephenturner** [comment]
Also needs meryl for building kmer dbs for merqury

**Comment by chriswyatt1** [comment]
Could you add a PR?. May be easier to think about how to integrate it

**Comment by stephenturner** [comment]
Draft PR in #63 with more info
