### ISSUE TITLE
Logic for variable input types

### ISSUE THREAD

**Issue by chriswyatt1** [nf-core/genomeqc#50]
It should work for genome only if there are only genome, or genome_annotation if only genomes with annotations. 

But we also need to test how the pipeline deals with mixed input. It run both subworkflows, and potentially all genomes separately.

**Comment by FernandoDuarteF** [comment]
I need to fix input validation for genome only samplesheet.

**Comment by chriswyatt1** [comment]
We need various input data samplesheets for the test data. 

Then these data also need to be on nf-core test datasets

**Comment by FernandoDuarteF** [comment]
See #57.

**Comment by FernandoDuarteF** [comment]
Solved in [49a21b3](https://github.com/nf-core/genomeqc/commit/49a21b3fbb937929540cc78cdbf6944c7c48eb1b).
