### ISSUE TITLE
Add test data

### ISSUE THREAD

**Issue by chriswyatt1** [nf-core/genomeqc#6]
We need a small test dataset for the whole pipeline, following nf-core guides. 

I think this could be just two chromosomes (or parts of chromosomes that are orthologous). Could be super small, like 10000bp total. I am pretty sure all the code will work on tiny chromosomes.

**Comment by chriswyatt1** [comment]
Hopefully done here:
https://github.com/nf-core/test-datasets/pull/1339

Used just two mycoplasma genomes 2000 lines, and 300 lines of their gff files. Maybe a little too small, but working with gffread and orthofinder.

**Comment by FernandoDuarteF** [comment]
We should probably use the 4-field format, whether running with local files or RefSeq IDs

**Comment by FernandoDuarteF** [comment]
Solved and included in the test config. See nf-core/test-datasets#1343

**Comment by FernandoDuarteF** [comment]
Add test profile to pipeline.
