### ISSUE TITLE
Merqury inputs should use database+assembly (fasta, not fastq)

### ISSUE THREAD

**Issue by stephenturner** [nf-core/genomeqc#75]
Merqury inputs should include the meryl db (created from reads), and the _assembly_. 

https://github.com/nf-core/genomeqc/blob/5e5f897730524eb771aa574920a42064876f1ea1/modules/nf-core/merqury/merqury/main.nf#L11-L12

Typo in the current implementation that joins to the reads (fasta), not the assembly.

https://github.com/nf-core/genomeqc/blob/5e5f897730524eb771aa574920a42064876f1ea1/workflows/genomeqc.nf#L127-L129

Need to change this to fasta, not fastq.

Also need to change this in the subworkflow nf-core/modules#6905

**Comment by FernandoDuarteF** [comment]
Fixed here [49a21b3](https://github.com/nf-core/genomeqc/commit/49a21b3fbb937929540cc78cdbf6944c7c48eb1b).
